images:
  - image: quay.io/cidverse/helmfile:${{TAG}}
    provides:
      - binary: helm
        version: ${{VERSION}}
    cache:
      - id: registry-auth
        dir: /app/.config/helm/registry
      - id: helm-config
        dir: /app/.config/helm
      - id: helm-cache
        dir: /app/.cache/helm/cache
      - id: helm-plugins
        dir: /app/.cache/helm/plugins
      - id: helm-repository
        dir: /app/.cache/helm/repository
    source:
      registry_url: quay.io/cidverse/helmfile
