images:
  - image: quay.io/cidverse/ansible:${{TAG}}
    provides:
      - binary: ansible
        version: ${{VERSION}}
      - binary: ansible-galaxy
        version: ${{VERSION}}
      - binary: ansible-playbook
        version: ${{VERSION}}
    cache:
      - id: ansible
        dir: /app/.ansible
    source:
      registry_url: quay.io/cidverse/ansible
