images:
  - image: quay.io/cidverse/ansible-lint:${{TAG}}
    provides:
      - binary: ansible-lint
        version: ${{VERSION}}
    cache:
      - id: ansible
        dir: /app/.ansible
    source:
      registry_url: quay.io/cidverse/ansible-lint
