actions:
  - name: mkdocs-start
    category: dev
    description: |
      Starts the mkdocs server for local development.
    type: container
    container:
      image: quay.io/cidverse/cid-actions-go:latest
      command: central run mkdocs-start
    scope: module
    rules:
      - type: cel
        expression: MODULE_BUILD_SYSTEM == "mkdocs" && MODULE_BUILD_SYSTEM_SYNTAX == "default"
  - name: mkdocs-build
    category: build
    description: |
      Builds the mkdocs project and stores the generated static files for later publication.
    type: container
    container:
      image: quay.io/cidverse/cid-actions-go:latest
      command: central run mkdocs-build
    scope: module
    rules:
      - type: cel
        expression: MODULE_BUILD_SYSTEM == "mkdocs" && MODULE_BUILD_SYSTEM_SYNTAX == "default"
