# name
name: ci

# triggers
on:
  workflow_call:
    inputs:
      cid-workflow:
        required: true
        type: string
        default: "main"
      cid-version:
        required: true
        type: string
        default: "0.1.0"
      job-pages:
        required: false
        type: boolean
        default: false
      cid-loglevel:
        description: 'Log level'
        required: false
        default: 'info'
        type: string
    secrets:
      # qodana
      QODANA_TOKEN:
        required: false
      # sonarcloud
      SONAR_HOST_URL:
        required: false
      SONAR_TOKEN:
        required: false
      SONAR_ORGANIZATION:
        required: false

# permissions, see https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions and https://docs.github.com/en/rest/overview/permissions-required-for-github-apps
permissions:
  actions: none
  checks: none
  contents: read
  deployments: none
  id-token: none
  issues: none
  packages: none
  pages: none
  pull-requests: none
  repository-projects: none
  security-events: none
  statuses: none

# cancel in progress when a new run starts
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

# jobs
jobs:
  # info
  info:
    name: Info
    runs-on: ubuntu-latest
    steps:
      - name: prepare environment
        uses: cidverse/ghact-cid-setup@main
        with:
          version: ${{ inputs.cid-version }}
      - name: checkout
        uses: actions/checkout@v3.5.2
        with:
          fetch-depth: 0
      - name: info
        env:
          CID_LOGLEVEL: ${{ inputs.cid-loglevel }}
        run: |
          echo "> project modules"
          cid --log-level=${CID_LOGLEVEL:-info} module ls
          echo "> catalog"
          cid --log-level=${CID_LOGLEVEL:-info} catalog list
          echo "> workflows"
          cid --log-level=${CID_LOGLEVEL:-info} workflow ls

  # build
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      id-token: write # provenance signing
    steps:
      - name: prepare environment
        uses: cidverse/ghact-cid-setup@main
        with:
          version: ${{ inputs.cid-version }}
      - name: checkout
        uses: actions/checkout@v3.5.2
        with:
          fetch-depth: 0
      - name: build
        env:
          CID_WORKFLOW: ${{ inputs.cid-workflow }}
          CID_LOGLEVEL: ${{ inputs.cid-loglevel }}
        run: |
          cid --log-level=${CID_LOGLEVEL:-info} workflow run "$CID_WORKFLOW" --stage build
      - name: upload artifacts
        uses: actions/upload-artifact@v3.1.2
        with:
          name: build-${{ github.run_id }}
          path: .dist
          retention-days: 1
          if-no-files-found: ignore
      - name: github pages artifact
        if: inputs.job-pages == true
        uses: actions/upload-pages-artifact@v1
        with:
          path: .dist/cidverse-github-io/html/docs/

  # test
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: prepare environment
        uses: cidverse/ghact-cid-setup@main
        with:
          version: ${{ inputs.cid-version }}
      - name: checkout
        uses: actions/checkout@v3.5.2
        with:
          fetch-depth: 0
      - name: test
        env:
          CID_WORKFLOW: ${{ inputs.cid-workflow }}
          CID_LOGLEVEL: ${{ inputs.cid-loglevel }}
        run: |
          cid --log-level=${CID_LOGLEVEL:-info} workflow run "$CID_WORKFLOW" --stage test
      - name: upload artifacts
        uses: actions/upload-artifact@v3.1.2
        with:
          name: test-${{ github.run_id }}
          path: .dist
          retention-days: 1
          if-no-files-found: ignore

  # scan
  scan:
    name: Scan
    runs-on: ubuntu-latest
    needs: [build, test]
    permissions:
      security-events: write
    steps:
      - name: prepare environment
        uses: cidverse/ghact-cid-setup@main
        with:
          version: ${{ inputs.cid-version }}
      - name: checkout
        uses: actions/checkout@v3.5.2
        with:
          fetch-depth: 0
      - name: download artifacts > build
        uses: actions/download-artifact@v3.0.2
        with:
          name: build-${{ github.run_id }}
          path: .dist
        continue-on-error: true
      - name: download artifacts > test
        uses: actions/download-artifact@v3.0.2
        with:
          name: test-${{ github.run_id }}
          path: .dist
        continue-on-error: true
      - name: scan
        env:
          CID_WORKFLOW: ${{ inputs.cid-workflow }}
          CID_LOGLEVEL: ${{ inputs.cid-loglevel }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_ORGANIZATION: ${{ secrets.SONAR_ORGANIZATION }}
        run: |
          cid --log-level=${CID_LOGLEVEL:-info} workflow run "$CID_WORKFLOW" --stage scan

  # package
  package:
    name: Package
    runs-on: ubuntu-latest
    needs: [build]
    permissions:
      id-token: write # provenance signing
    steps:
      - name: prepare environment
        uses: cidverse/ghact-cid-setup@main
        with:
          version: ${{ inputs.cid-version }}
      - name: checkout
        uses: actions/checkout@v3.5.2
        with:
          fetch-depth: 0
      - name: download artifacts > build
        uses: actions/download-artifact@v3.0.2
        with:
          name: build-${{ github.run_id }}
          path: .dist
        continue-on-error: true
      - name: package
        env:
          CID_WORKFLOW: ${{ inputs.cid-workflow }}
          CID_LOGLEVEL: ${{ inputs.cid-loglevel }}
        run: |
          cid --log-level=${CID_LOGLEVEL:-info} workflow run "$CID_WORKFLOW" --stage package
      - name: upload artifacts
        uses: actions/upload-artifact@v3.1.2
        with:
          name: package-${{ github.run_id }}
          path: .dist
          retention-days: 1
          if-no-files-found: ignore

  # publish
  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: [package, scan]
    permissions:
      # create release
      contents: write
    if: github.event.name != 'pull_request'
    steps:
      - name: prepare environment
        uses: cidverse/ghact-cid-setup@main
        with:
          version: ${{ inputs.cid-version }}
      - name: checkout
        uses: actions/checkout@v3.5.2
        with:
          fetch-depth: 0
      - name: download artifacts > build
        uses: actions/download-artifact@v3.0.2
        with:
          name: build-${{ github.run_id }}
          path: .dist
        continue-on-error: true
      - name: download artifacts > build
        uses: actions/download-artifact@v3.0.2
        with:
          name: package-${{ github.run_id }}
          path: .dist
        continue-on-error: true
      - name: publish
        env:
          CID_WORKFLOW: ${{ inputs.cid-workflow }}
          CID_LOGLEVEL: ${{ inputs.cid-loglevel }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cid --log-level=${CID_LOGLEVEL:-info} workflow run "$CID_WORKFLOW" --stage publish

  # Pages
  pages:
    name: Pages
    runs-on: ubuntu-latest
    needs: [scan]
    permissions:
      pages: write
      id-token: write
    if: github.event.name != 'pull_request' && inputs.job-pages == true
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2.0.1
